# Generated by Django 5.1.4 on 2025-06-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
