# Generated by Django 5.1.4 on 2025-06-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_registroasistencia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tipoasistencia',
            name='nombre_asistencia',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
