# Generated by Django 5.1.4 on 2025-10-21 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registroasistencia_fingerprint_alter_empleado_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codigo_qr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DispositivoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=100, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
            ],
        ),
    ]
