# Generated by hand for local use: create table for ActividadProyecto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dispositivoempleado_and_empleado_codigoqr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=models.deletion.CASCADE, to='app.empleado')),
            ],
        ),
    ]
