# Generated by Django; add unique constraint on ActividadProyecto (empleado, fecha)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_reset_dispositivos'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actividadproyecto',
            constraint=models.UniqueConstraint(fields=('empleado', 'fecha'), name='uniq_actividadpor_dia'),
        ),
    ]
