# Generated by Django 5.1.4 on 2025-11-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_actividadproyecto_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='dni',
        ),
    ]
